### ISSUE TITLE
1.0.6 or later Not working with official VR.

### ISSUE THREAD

**Issue by sione999** [IllusionMods/AnimationLoader#12]
About Koikatsu.
It can be used normally in studio and free H.
However, VERs after 1.0.6 do not seem to work properly in official VR.

**Comment by Keelhauled** [comment]
Can you send your output_log from when the bug happens?

**Comment by sione999** [comment]
sure.
The phenomenon is simply that the list does not show up.

[output_log - cop.txt](https://github.com/IllusionMods/AnimationLoader/files/6687438/output_log.-.cop.txt)

**Comment by Keelhauled** [comment]
Forcing grid UI for VR to fix this 0b5c529c4ccf05476fea7b30ee8f9c55496214d7
