### ISSUE TITLE
Problem when using plugin with update

### ISSUE THREAD

**Issue by IDontHaveIdea** [IllusionMods/AnimationLoader#15]
When the plugin is compiled with the update:

@nhydock Integrate new animations more seamlessly with base game data structures (#14)

The new animations load but don't work as expected.  There is no random dialog, no precum action and the scene does not really finish even manually.  The scene can finish if you switch to an original animation.

Original game animations have no problem.

**Comment by nhydock** [comment]
I started to notice this too and didn't know if it was the changes I made here or if it was another plugin I was working on.  I'll do some digging to see what values I might have gotten wrong when moving some code around.

**Comment by nhydock** [comment]
It looks like there are a few places in koikatsu relating to voice controllers that rely specifically on animation id, so I can't just have unique ones :(
