### ISSUE TITLE
Koikatsu Sunshine support?

### ISSUE THREAD

**Issue by Elionna** [IllusionMods/AnimationLoader#19]
This is a pretty incredible mod, was wondering if it can be updated for KKS?

**Comment by ManlyMarco** [comment]
It can but no one seems willing so far.

**Comment by IDontHaveIdea** [comment]
Hi,

I am working on a port.

https://github.com/IDontHaveIdea/AnimationLoader/releases/tag/1.0.9a2

**Comment by IDontHaveIdea** [comment]
KKS port.

[Release 1.1.0](https://github.com/IllusionMods/AnimationLoader/releases/tag/1.1.0)
