### ISSUE TITLE
[KKS] all additional animations not showing up in story mode

### ISSUE THREAD

**Issue by Elionna** [IllusionMods/AnimationLoader#21]
All the additional animations sometimes don't show up in story mode. They always how up properly in Free H. 

<see below>

All my characters are maxed out experience wise. 

Full List:
![full anim](https://user-images.githubusercontent.com/22693130/147799544-792acf85-039b-4541-b1c6-0c55ec46dc9b.png)

Missing List:
![missing anim](https://user-images.githubusercontent.com/22693130/147799553-8962a3ee-b3a9-4176-aec2-1799cdec25a1.png)

**Comment by ManlyMarco** [comment]
What animations are shown depends on the experience level of the character I believe. More experienced will get more animations.

**Comment by IDontHaveIdea** [comment]
To compare what animations are shown the characters must have an equivalent experience level.  These change at 50%, 75% and 100%.  A character with 80% experience should have more animations available than one with 36% for example.

**Comment by Elionna** [comment]
Hi all my characters are maxxed out experience wise so that's not the problem.

**Comment by Elionna** [comment]
I figured out the problem, all the characters that were imported **after** the animation loader plugin was added to my game have all the animations.

However, all the characters that were imported before the animation loader plugin do not have access to all the new animations despite being max level. (Which was shown in my second picture in my original post)

I think in future updates if new animations are added, it may mean that you will have to reset the character (so remove from booking and rebook them) each time in order to gain access to new animations which can be cumbersome as it removes progress. 

But if anyone has a similar problem like me, removing the character and maxing her out again seems to fix the issue.

Character who had missing animations fixed after removing from booking and adding her again:
![Screenshot (42)](https://user-images.githubusercontent.com/22693130/147843508-44343839-4ce5-48d1-8184-b9c9b403165b.png)

**Comment by IDontHaveIdea** [comment]
Hi,

Do maintain a local version of the animations manifest for changing names for example?

**Comment by Elionna** [comment]
> Hi,
> 
> Do you maintain a local version of the animations manifest for changing names for example?

I do not, only things in MyMods folder is what is supplied in the repo

<img width="583" alt="folder" src="https://user-images.githubusercontent.com/22693130/147867005-e41cf88e-6271-49d9-81d2-5126745a971a.png">

**Comment by IDontHaveIdea** [comment]
I'm unable to replicate this I have no way to find the cause.

Wait for the next major update and reopen if it still persists and please attach a full outupt_log.txt.
