### ISSUE TITLE
KKS VR support

### ISSUE THREAD

**Issue by dizzy-gh** [IllusionMods/AnimationLoader#22]
Are there any plans for KKS VR support in the future?

It works great for regular KK but it doesn't seem the KKS version implements GridUI so the positions don't show up in VR. Would it still be possible to get it to work in VR without GridUI?

Fantastic plugin, by the way. Always wanted a way to import animations without adding features I didn't need. Cheers!

**Comment by IDontHaveIdea** [comment]
Hi,

Can you test this and upload the output_log.txt here.

https://github.com/IllusionMods/AnimationLoader/releases/download/v1.1.0.1/AnimationLoader.KoikatsuSunshine.VR.v1.1.0.1.zip

I know that for KK the grid is needed for VR to work.  Is this also the case for KKS? If is not necessary will it be more convenient to have the GridUI. I'm thinking about the space required for the grid if the number of animations continues to grow the grid may eventually have to be scrollable. A search facility is on queue right now.

**Comment by dizzy-gh** [comment]
https://pastebin.com/36R6ttc5

[Info   :   BepInEx] Loading [Animation Loader VR 1.1.0.1]
NullReferenceException: Object reference not set to an instance of an object

void KKAPI.MainGame.GameAPI.RegisterExtraBehaviour<AnimationLoaderGameController>(string)
void AnimationLoader.SwapAnim.Awake()
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
AssetBundleManager:InitializeBeforeSceneLoad()
 
(Filename:  Line: -1)

Causes Free-H to infinite load.

**Comment by dizzy-gh** [comment]
Using BR 2.2 btw. Had to update KKSAPI since the one in the repack is old.

**Comment by IDontHaveIdea** [comment]
I don't have VR equipment that is why I have to ask for testing.

I remove the "New" animations tracking code to see if it loads now.

[AnimationLoader.KoikatsuSunshine.VR-1.zip](https://github.com/IllusionMods/AnimationLoader/files/8008035/AnimationLoader.KoikatsuSunshine.VR-1.zip)

**Comment by dizzy-gh** [comment]
https://pastebin.com/TubgmsgA

It works! Thank you!

**Comment by IDontHaveIdea** [comment]
There is a new version [1.1.0.3](https://github.com/IllusionMods/AnimationLoader/releases/tag/v1.1.0.3) a single dll for standard and VR.  It needs [KKAPI 1.31.2](https://github.com/IllusionMods/IllusionModdingAPI/releases/tag/v1.31.2) to work.

Any new behavior that was added can be turn-off in the configuration manager.  Re-open if there are any problems.
