### ISSUE TITLE
[KK] 3P mode insertion bug: non-vanilla animations does not switch girls properly

### ISSUE THREAD

**Issue by Dudexploring** [IllusionMods/AnimationLoader#29]
When non-vanilla 3p (insert) animations is played, the girls position would switch, but not who the system thinks is being inserted.

Example: "Doggy & Cunnilingus" selected, Girl 1 is to be inserted, and Girl 2 gets to be 'pleasured'. When I switch to "Doggy & Cunnilingus (Switch Girl)," the game swaps the positions of the 2 Girls, but Girl 1 is the one who is to be 'inserted.' and Girl 2, despite looking to be the one being inserted, is not actually so according to the game. In this case, Girl 1, with position swapped, who is about to receive cunnilingus from Girl 2, is being 'remotely' inserted by the player, and any 'finishing effects' will apply to Girl 1, who is not supposed to be 'inserted' in this case.

Swapping girls with vanilla animations works perfectly fine with the Girls actually swapping places.

**Comment by ManlyMarco** [comment]
Does this happen in all or only some of the custom 3P animations?

**Comment by Dudexploring** [comment]
Only the animations provided by the HF patch and the Update via the launcher. 
"Doggy & Cunnilingus" and "Missionary & Fingering 2"

**Comment by IDontHaveIdea** [comment]
I have to do more research on this. Will be disabled until solution is found.

**Comment by IDontHaveIdea** [comment]
Problem solved on next version:
AnimationLoader 1.1.3 - Problem with motion IK setting
[katarsys] KPlug Animations v1.5.zipmod - Solves target problem on (Switch Girl)
[katarsys] KPlug Animation Bundles 3.1 pack - KPlug Animations v1.5 make reference to animations found on this bundle only if used with prior bundles it will cause problems when such animations are selected.

**Comment by IDontHaveIdea** [comment]
New release is out. The issue should be solved.

**Comment by Dudexploring** [comment]
I've tested the new release, bug has been fixed. Thanks guys.
