### ISSUE TITLE
[KKS Feature Request]: Support lesbian animation choose in game

### ISSUE THREAD

**Issue by QingXia-Ela** [IllusionMods/AnimationLoader#30]
As the title suggestion. Is it possible to achieve this requirement?
Request details:
1. Add position slot in Free-H lesbian mode.In vanilla game Free-H lesbian mode only have 3 slot. Does it is possible to add more slot for more animation?
![图片](https://user-images.githubusercontent.com/86217807/230749849-a5ae3256-32ae-4745-bbdc-d07075d416ca.png)
2. Lesbian animation in zipmod can be used in story mode randomly.Just like two girls trigger lesbian event on lie down, and there is a probability to use the animation in zipmod instead vanilla.

If you are willing to implement the above requirements, I will be very grateful!
If it is not convenient for you, you can also talk about the implementation idea, and then I will study it and try to implement it by myself!

Thanks!

**Comment by ManlyMarco** [comment]
So in short you want to be able to access lesbian animation points from normal H?

**Comment by QingXia-Ela** [comment]
No, I mean access lesbian animation points from Lesbian H.
![图片](https://user-images.githubusercontent.com/86217807/230759243-4275fbda-002a-49e7-97e1-c5d88900d2ab.png)
And I found that some lesbian animation made by Katarsys were loaded in game. But I don't know how to use it.
```
From G:\hentai\KKS\wzV17038PC\KKS\mods\Sideloader Modpack - Animations\Katarsys\[katarsys] KPlug Animations v1.5.zipmod kpluganim-1.5: Root elements of AnimationLoader
...
kpluganim-sonyu3P-khs3_f_02_00-7000 - Missionary & Fingering 2
kpluganim-sonyu3P-khs3_f_02_01-7001 - Missionary & Fingering 2 (Switch Girl)
kpluganim-sonyu3P-khs3_f_03_00-7002 - Doggy & Cunnilingus
kpluganim-sonyu3P-khs3_f_03_01-7003 - Doggy & Cunnilingus (Switch Girl)
kpluganim-lesbian-khr_f_05_00-5000 - Cunnilingus Lying # --- Loaded ---
```

**Comment by IDontHaveIdea** [comment]
The lesbian animations are not loaded quite the same way as the other types.  I work on them every now and then still haven't found why the are ignored. Using the same techniques to hook them to the game as the others doesn't work.

**Comment by QingXia-Ela** [comment]
> @IDontHaveIdea Okay, and one more thing is I have saw this on ph: https://cn.pornhub.com/view_video.php?viewkey=ph63cade3c09a9b. It seems that it was successfully to load katarsys lesbian animation in game.So it means koikatu is support lesbian animation choose but unsupport in KKS?

Thanks you guys to answer my foolish question. I found that the anime in KK were used kPlug to load and Press "U" to open pose selector.

kPlug and ksPlug update: https://kemono.party/patreon/user/12062995/
