### ISSUE TITLE
Broken animation when changing or taking off the female character's outfit

### ISSUE THREAD

**Issue by TheF3nt0n** [IllusionMods/AnimationLoader#7]
So, I noticed this bug a while ago, when you change or take off the female character's outfit while using any of the custom H animations, the female character's animation will be broken. The only workaround to fix this is switching to another animation. This bug does not happen with the original H animations because things are working like usual.

It is really annoying to switch to an original H animation just to change the character's outfit. I don't know if this bug is related to the plugin or a bug that directly came from the animations pack itself.

**Comment by Keelhauled** [comment]
I'm not seeing the bug gotta say. Probably something unrelated to this plugin.

**Comment by TheF3nt0n** [comment]
That's weird, this hasn't happened to me before, I'm only using KPlug animations.

**Comment by Keelhauled** [comment]
Did you find out the cause?

**Comment by TheF3nt0n** [comment]
I think it's caused by the bone mod of a character, I used another character's bone mod for my own character and then most of the bug is gone, though taking off the shoes while using the custom animation still makes the bone broken.
