### ISSUE TITLE
Noob guide on where to download custom animations / Convert kPlug animations to be compatible with this mod? 

### ISSUE THREAD

**Issue by Elionna** [IllusionMods/AnimationLoader#8]
Really awesome mod, being able to add custom animations is huge, but not sure how to use it.

**Comment by Keelhauled** [comment]
Sure i can add something

**Comment by Keelhauled** [comment]
Done https://github.com/IllusionMods/AnimationLoader/commit/c26a969ca8e70a0cfa35c371d45a795100af3a81
